name: "Web-Beest - Site admininistration"
description: "Modules for Drupal site administration" 
type: "Admin"
install:
  - block_class
  - storybook
  - styleguide
config:
  import:
    block_class: '*'
    storybook: '*'
    styleguide: '*'
  strict: false
  actions:
    user.role.anonymous:
      grantPermissions:
        - 'render storybook stories'
    user.role.administrator:
      createIfNotExists:
        label: 'Administrator'
      grantPermissions:
        - 'view style guides'
